[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.fmt]
single-line-func-calls = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/"
]

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }